spring:
  datasource:  
    url: jdbc:oracle:thin:@ora64:1521:adat
    username: Pre_5M
    password: pre_5m
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate   
    show-sql: true
  application:
    name: HTLCRM
server:
    port: 1234 
